services:
  db:
    container_name: postgres_fiber_db
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGHOST: localhost
      PGPORT: 5432
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
  redis:
    container_name: redis_fiber_cache
    image: redis:7.0.11
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data/redis